Update bootstrap

diff --git a/.config/yadm/bootstrap b/.config/yadm/bootstrap
--- a/.config/yadm/bootstrap
+++ b/.config/yadm/bootstrap
@@ -1,5 +1,29 @@
+required=(npm curl)
+
+check_programs() {
+  local missing=()
+  for prog do
+    if ! command -v $prog &> /dev/null; then
+      missing+=($prog)
+    fi
+  done
+  if (( ${#missing[@]} )); then
+    echo "Please install missing programs and run 'yadm bootstrap':"
+    echo "-> ${missing[*]}"
+    exit
+  fi
+}
+
+check_programs "${required[@]}"
+
+
 # Install packages for CoC
 npm --prefix $HOME/.config/coc/extensions install $HOME/.config/coc/extensions
 
+# Install vim-plug
+sh -c 'curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs \
+       https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
+nvim +'PlugInstall --sync' +qa
+
 # Oh-my-zsh
-ZSH=$HOME/.config/zsh/oh-my-zsh KEEP_ZSHRC=yes sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended
+#ZSH=$HOME/.config/zsh/oh-my-zsh KEEP_ZSHRC=yes sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended
